// packages/sdks/snippets/react/src/routes/blueprints/ProductEditorial.tsx
import {
  KhulnasoftContent,
  Content,
  fetchOneEntry,
  isPreviewing,
} from '@khulnasoft.com/sdk-react';
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import ProductFooter from '../../components/ProductFooter';
import ProductHeader from '../../components/ProductHeader';
import ProductInfo, { type Product } from '../../components/ProductInfo';

const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';
const MODEL_NAME = 'product-editorial';

export default function ProductEditorial() {
  const [product, setProduct] = useState<Product | null>(null);
  const [editorial, setEditorial] = useState<KhulnasoftContent | null>(null);
  const { id } = useParams();

  useEffect(() => {
    fetch(`https://fakestoreapi.com/products/${id}`)
      .then((res) => res.json())
      .then((productData) => {
        setProduct(productData);
      });
  }, [id]);

  useEffect(() => {
    fetchOneEntry({
      model: MODEL_NAME,
      apiKey: API_KEY,
      userAttributes: { urlPath: window.location.pathname },
    }).then((editorialData) => {
      setEditorial(editorialData);
    });
  }, []);

  if (!isPreviewing() && !product && !editorial) return <div>404</div>;

  return (
    <>
      <ProductHeader />
      <ProductInfo product={product} />
      {/* Render Khulnasoft content below */}
      <Content model={MODEL_NAME} content={editorial} apiKey={API_KEY} />
      <ProductFooter />
    </>
  );
}

// packages/sdks/snippets/angular-16/src/app/product-editorial/product-editorial.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import {
  Content,
  fetchOneEntry,
  type KhulnasoftContent,
} from '@khulnasoft.com/sdk-angular';
import { FooterComponent } from './footer/footer.component';
import { HeaderComponent } from './header/header.component';
import { ProductInfoComponent } from './product-info/product-info.component';

@Component({
  selector: 'app-product-editorial',
  standalone: true,
  imports: [
    Content,
    CommonModule,
    ProductInfoComponent,
    HeaderComponent,
    FooterComponent,
  ],
  template: `
    <app-header />

    <app-product-info [product]="product" />

    <khulnasoft-content [content]="editorial" model="product-editorial" />

    <app-footer />
  `,
})
export class ProductEditorialComponent {
  product: any;
  editorial: KhulnasoftContent | null = null;
  productId?: string;

  async ngOnInit() {
    this.productId = window.location.pathname.split('/').pop() || '';
    if (this.productId) {
      await this.fetchProductAndEditorial();
    }
  }

  private async fetchProductAndEditorial() {
    // Fetch product data from external API or your own CMS
    this.product = await fetch(
      `https://fakestoreapi.com/products/${this.productId}`
    ).then((res) => res.json());

    // Fetch editorial content from Khulnasoft.com
    this.editorial = await fetchOneEntry({
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
      model: 'product-editorial',
      userAttributes: {
        urlPath: window.location.pathname || '/',
      },
    });
  }
}
