// packages/sdks/snippets/react-sdk-next-pages/src/pages/product-details/product/category/[handle].tsx
import { fetchOneEntry, type KhulnasoftContent } from '@khulnasoft.com/sdk-react';
import type { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import Image from 'next/image';

export const getServerSideProps = (async ({ params }) => {
  const productDetails = await fetchOneEntry({
    model: 'product-details',
    apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
    query: {
      'data.handle': params?.handle,
    },
  });

  return { props: { productDetails } };
}) satisfies GetServerSideProps<{
  productDetails: KhulnasoftContent | null;
}>;

export default function ProductCategoryPage({
  productDetails,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    productDetails && (
      <div className="product-details-page">
        <h1>{productDetails.data?.name}</h1>
        <Image
          src={productDetails.data?.image}
          alt={productDetails.data?.name}
          priority={true}
        />
        <p>{productDetails.data?.collection.value.data.copy}</p>
        <p>Price: {productDetails.data?.collection.value.data.price}</p>
      </div>
    )
  );
}

// packages/sdks/snippets/nuxt/pages/product/category/[handle].vue
<script setup lang="ts">
import { useAsyncData } from '#app';
import { fetchOneEntry } from '@khulnasoft.com/sdk-vue';
import { useRoute } from 'nuxt/app';

const route = useRoute();
const { data: productDetails, pending } = await useAsyncData(
  'product-details',
  () =>
    fetchOneEntry({
      model: 'product-details',
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
      query: {
        'data.handle': route.params.handle,
      },
    })
);
</script>

<template>
  <div v-if="pending">Loading product details...</div>

  <div class="product-details-page" v-if="productDetails?.data">
    <h1>{{ productDetails.data.name }}</h1>
    <img :src="productDetails.data.image" :alt="productDetails.data.name" />
    <p>{{ productDetails.data.collection.value.data.copy }}</p>
    <p>Price: {{ productDetails.data.collection.value.data.price }}</p>
  </div>
</template>
