// packages/sdks/snippets/qwik-city/src/routes/advanced-child/index.tsx
import { component$ } from '@khulnasoft.com/qwik';
import { routeLoader$ } from '@khulnasoft.com/qwik-city';
import { Content, fetchOneEntry, isPreviewing } from '@khulnasoft.com/sdk-qwik';
import { customTabsInfo } from '~/components/CustomTabs';

const MODEL = 'advanced-child';
const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';

export const useCustomChild = routeLoader$(async ({ url }) => {
  return await fetchOneEntry({
    model: MODEL,
    apiKey: API_KEY,
    userAttributes: {
      urlPath: url.pathname,
    },
  });
});

export default component$(() => {
  const content = useCustomChild();

  if (!content.value && !isPreviewing()) {
    return <div>404</div>;
  }
  return (
    <Content
      model={MODEL}
      content={content.value}
      apiKey={API_KEY}
      customComponents={[customTabsInfo]}
    />
  );
});

// packages/sdks/snippets/svelte/src/components/advanced-child/AdvancedChild.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Content, fetchOneEntry, isPreviewing } from '@khulnasoft.com/sdk-svelte';
  import type { KhulnasoftContent } from '@khulnasoft.com/sdk-svelte';
  import { CustomTabsInfo } from './CustomTabsInfo';

  let loading = true;
  let content: KhulnasoftContent | null;

  let model = 'advanced-child';
  let apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

  onMount(() => {
    fetchOneEntry({
      model,
      apiKey,
      userAttributes: {
        urlPath: window.location.pathname,
      },
    }).then((data) => {
      content = data;
      loading = false;
    });
  });
</script>

{#if loading}
  <div>Loading...</div>
{:else if !content && !isPreviewing()}
  <div>404 - Not Found</div>
{:else}
  <Content {content} {apiKey} {model} customComponents={[CustomTabsInfo]} />
{/if}
