// packages/sdks/snippets/angular-16-ssr/src/app/custom-child/custom-hero/custom-hero.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import type { RegisteredComponent } from '@khulnasoft.com/sdk-angular';

@Component({
  selector: 'app-custom-hero',
  standalone: true,
  imports: [CommonModule],
  template: ` <div>This is text from your component</div> `,
})
export class CustomHeroComponent {}

export const customHeroInfo: RegisteredComponent = {
  component: CustomHeroComponent,
  name: 'CustomHero',
  inputs: [],
  canHaveChildren: true,
  defaultChildren: [
    {
      '@type': '@khulnasoft.com/sdk:Element',
      component: {
        name: 'Text',
        options: {
          text: 'This is Khulnasoft text',
        },
      },
    },
  ],
};

// packages/sdks/snippets/react/src/components/CustomHero.tsx
import { RegisteredComponent } from '@khulnasoft.com/sdk-react';
import { ReactNode } from 'react';

interface CustomHeroProps {
  children: ReactNode;
}

const CustomHero = (props: CustomHeroProps) => {
  return (
    <>
      <div>This is text from your component</div>

      {props.children}
    </>
  );
};

export const customHeroInfo: RegisteredComponent = {
  component: CustomHero,
  name: 'CustomHero',
  inputs: [],
  canHaveChildren: true,
  defaultChildren: [
    {
      '@type': '@khulnasoft.com/sdk:Element',
      component: {
        name: 'Text',
        options: {
          text: 'This is Khulnasoft text',
        },
      },
    },
  ],
};
