// packages/sdks/snippets/nuxt/pages/custom-child.vue
<script setup lang="ts">
import { fetchOneEntry, Content, isPreviewing } from '@khulnasoft.com/sdk-vue';
import CustomHeroInfo from '../components/CustomHeroInfo';
import { useRoute } from 'nuxt/app';

const route = useRoute();
const model = 'custom-child';
const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

const { data: content, pending } = await useAsyncData(
  `khulnasoft-${model}-${route.path}`,
  () =>
    fetchOneEntry({
      model,
      apiKey,
      userAttributes: {
        urlPath: route.path,
      },
    })
);
</script>

<template>
  <div v-if="pending">Loading...</div>
  <div v-else-if="!content && !isPreviewing()">404 - Not Found</div>
  <Content
    v-else
    :content="content"
    :model="model"
    :apiKey="apiKey"
    :customComponents="[CustomHeroInfo]"
  />
</template>

// packages/sdks/snippets/sveltekit/src/routes/custom-child/+page.svelte
<script lang="ts">
  import { Content, isPreviewing } from '@khulnasoft.com/sdk-svelte';
  import type { PageData } from './$types';
  import { customHeroInfo } from './CustomHeroInfo';

  export let data: PageData;
</script>

{#if !data.data && !isPreviewing()}
  <div>404 - Not Found</div>
{:else}
  <Content
    content={data.data}
    apiKey="ee9f13b4981e489a9a1209887695ef2b"
    model="custom-child"
    customComponents={[customHeroInfo]}
  />
{/if}
