// packages/sdks/snippets/vue/src/views/EditableRegions.vue
<template>
  <div>
    <div v-if="loading">Loading...</div>
    <div v-else-if="!content && !isPreviewing()">404 - Not Found</div>
    <Content
      v-else
      :content="content"
      model="editable-regions"
      apiKey="ee9f13b4981e489a9a1209887695ef2b"
      :customComponents="[CustomColumnsInfo]"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import {
  Content,
  fetchOneEntry,
  isPreviewing,
  type KhulnasoftContent,
} from '@khulnasoft.com/sdk-vue';
import CustomColumnsInfo from '@/components/custom-components/custom-columns/CustomColumnsInfo';
import { useRoute } from 'vue-router';

const route = useRoute();
const content = ref<KhulnasoftContent | null>(null);
const loading = ref(true);

onMounted(() => {
  fetchOneEntry({
    model: 'editable-regions',
    apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
    userAttributes: { urlPath: route.path },
  })
    .then((result) => {
      content.value = result;
    })
    .finally(() => {
      loading.value = false;
    });
});
</script>

// packages/sdks/snippets/angular-16-ssr/src/app/editable-regions/editable-regions.component.ts
import { CommonModule } from '@angular/common';
import { Component, type OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Content, type KhulnasoftContent } from '@khulnasoft.com/sdk-angular';
import { customColumnsInfo } from './custom-columns/custom-columns.component';

@Component({
  selector: 'app-editable-region',
  standalone: true,
  imports: [CommonModule, Content],
  template: `
    <div *ngIf="content; else notFound">
      <khulnasoft-content
        [content]="content"
        [model]="model"
        [apiKey]="apiKey"
        [customComponents]="customComponents"
      />
    </div>
    <ng-template #notFound>404</ng-template>
  `,
})
export class EditableRegionComponent implements OnInit {
  model = 'page';
  apiKey = 'ee9f13b4981e489a9a1209887695ef2b';
  customComponents = [customColumnsInfo];
  content: KhulnasoftContent | null = null;

  constructor(private route: ActivatedRoute) {}

  async ngOnInit() {
    this.route.data.subscribe((data: any) => {
      this.content = data.content;
    });
  }
}
