// packages/sdks/snippets/hydrogen/app/components/CustomTabs.tsx
import {useState} from 'react';
import {
  Blocks,
  type KhulnasoftBlock,
  type RegisteredComponent,
} from '@khulnasoft.com/sdk-react';

interface CustomTabsProps {
  tabList: Array<{
    tabName: string;
    blocks: KhulnasoftBlock[];
  }>;
  khulnasoftBlock: KhulnasoftBlock;
}

export function CustomTabs({tabList, khulnasoftBlock}: CustomTabsProps) {
  const [activeTab, setActiveTab] = useState(0);

  if (!tabList?.length) return null;

  return (
    <>
      {tabList.map((tab, i) => (
        <button
          key={i}
          onClick={() => setActiveTab(i)}
          className={activeTab === i ? 'active' : ''}
        >
          {tab.tabName}
        </button>
      ))}

      <Blocks
        parent={khulnasoftBlock.id}
        path={`tabList.${activeTab}.blocks`}
        blocks={tabList[activeTab].blocks}
      />
    </>
  );
}

export const customTabsInfo: RegisteredComponent = {
  name: 'TabFields',
  component: CustomTabs,
  shouldReceiveKhulnasoftProps: {
    khulnasoftBlock: true,
  },
  inputs: [
    {
      name: 'tabList',
      type: 'list',
      subFields: [
        {name: 'tabName', type: 'string'},
        {name: 'blocks', type: 'uiBlocks', defaultValue: []},
      ],
    },
  ],
};

// packages/sdks/snippets/angular-16/src/app/advanced-child/custom-tabs/custom-tabs.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import type {
  KhulnasoftBlock,
  KhulnasoftContextInterface,
  RegisteredComponent,
  RegisteredComponents,
} from '@khulnasoft.com/sdk-angular';
import { Blocks } from '@khulnasoft.com/sdk-angular';

@Component({
  selector: 'app-custom-tabs',
  standalone: true,
  imports: [CommonModule, Blocks],
  template: `
    <ng-container *ngIf="tabList?.length">
      <button
        *ngFor="let tab of tabList; let i = index"
        [class.active]="activeTab === i"
        (click)="activeTab = i"
      >
        {{ tab.tabName }}
      </button>

      <blocks
        [blocks]="tabList[activeTab].blocks"
        [path]="'tabList.' + activeTab + '.blocks'"
        [parent]="khulnasoftBlock.id"
        [context]="khulnasoftContext"
        [registeredComponents]="khulnasoftComponents"
      />
    </ng-container>
  `,
})
export class CustomTabsComponent {
  @Input() khulnasoftBlock!: KhulnasoftBlock;
  @Input() tabList: { tabName: string; blocks: KhulnasoftBlock[] }[] = [];
  @Input() khulnasoftComponents: RegisteredComponents = {};
  @Input() khulnasoftContext!: KhulnasoftContextInterface;

  activeTab = 0;
}

export const customTabsInfo: RegisteredComponent = {
  component: CustomTabsComponent,
  name: 'TabFields',
  inputs: [
    {
      name: 'tabList',
      type: 'list',
      subFields: [
        {
          name: 'tabName',
          type: 'string',
        },
        {
          name: 'blocks',
          type: 'uiBlocks',
          defaultValue: [],
        },
      ],
    },
  ],
  shouldReceiveKhulnasoftProps: {
    khulnasoftBlock: true,
    khulnasoftComponents: true,
    khulnasoftContext: true,
  },
};
