// packages/sdks/snippets/svelte/src/components/blueprints/BlogArticle.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    fetchOneEntry,
    Content,
    isPreviewing,
    type KhulnasoftContent,
  } from '@khulnasoft.com/sdk-svelte';

  export let handle: string;
  let article: KhulnasoftContent | null;
  const model = 'blog-article';
  const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

  onMount(() => {
    fetchOneEntry({
      model,
      apiKey,
      query: { 'data.handle': handle },
    }).then((data) => {
      article = data;
    });
  });
</script>

{#if !article?.data && !isPreviewing()}
  <div>404</div>
{:else if article?.data}
  <div class="content">
    <h1>{article.data.title}</h1>
    <p>{article.data.blurb}</p>
    <img src={article.data.image} alt={article.data.title} />
    <Content {model} content={article} {apiKey} />
  </div>
{/if}

// packages/sdks/snippets/react/src/routes/blueprints/BlogArticle.tsx
import {
  KhulnasoftContent,
  Content,
  fetchOneEntry,
  isPreviewing,
} from '@khulnasoft.com/sdk-react';
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';

const model = 'blog-article';
const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

export default function BlogArticle() {
  const [article, setArticle] = useState<KhulnasoftContent | null>(null);
  const { handle } = useParams();

  useEffect(() => {
    fetchOneEntry({
      model,
      apiKey,
      query: {
        'data.handle': handle,
      },
    }).then((result) => {
      setArticle(result);
    });
  }, [handle]);

  if (!article && !isPreviewing()) {
    return <div>404</div>;
  }

  return (
    article?.data && (
      <div className="content">
        <h1>{article.data.title}</h1>
        <p>{article.data.blurb}</p>
        <img src={article.data.image} />
        <Content model={model} content={article} apiKey={apiKey} />
      </div>
    )
  );
}
