// packages/sdks/snippets/svelte/src/components/blueprints/ProductDetails.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fetchOneEntry, type KhulnasoftContent } from '@khulnasoft.com/sdk-svelte';

  export let handle: string;
  let productDetails: KhulnasoftContent | null = null;

  onMount(() => {
    fetchOneEntry({
      model: 'product-details',
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
      query: { 'data.handle': handle },
    }).then((data) => (productDetails = data));
  });
</script>

{#if !productDetails}
  <p>Loading product details...</p>
{:else}
  <div class="product-details-page">
    <h1>{productDetails.data?.name}</h1>
    <img src={productDetails.data?.image} alt={productDetails.data?.name} />
    <p>{productDetails.data?.collection.value.data.copy}</p>
    <p>Price: {productDetails.data?.collection.value.data.price}</p>
  </div>
{/if}

// packages/sdks/snippets/react/src/routes/blueprints/ProductDetails.tsx
import { KhulnasoftContent, fetchOneEntry } from '@khulnasoft.com/sdk-react';
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';

export default function ProductDetails() {
  const [productDetails, setProductDetails] = useState<KhulnasoftContent | null>(
    null
  );

  const { handle } = useParams();

  useEffect(() => {
    fetchOneEntry({
      model: 'product-details',
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
      query: {
        'data.handle': handle,
      },
    }).then((productData) => {
      setProductDetails(productData);
    });
  }, [handle]);

  if (!productDetails) {
    return <p>Loading product details...</p>;
  }

  return (
    <div className="product-details">
      <h1>{productDetails.data?.name}</h1>
      <img src={productDetails.data?.image} alt={productDetails.data?.name} />
      <p>{productDetails.data?.collection.value.data.copy}</p>
      <p>Price: {productDetails.data?.collection.value.data.price}</p>
    </div>
  );
}
