// packages/sdks/snippets/nuxt/pages/blogs/[handle].vue
<script setup lang="ts">
import { Content, fetchOneEntry } from '@khulnasoft.com/sdk-vue';
import { useRoute } from 'nuxt/app';

const model = 'blog-article';
const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';
const route = useRoute();

const { data: article } = await useAsyncData('blogArticle', () =>
  fetchOneEntry({
    model,
    apiKey: API_KEY,
    query: { 'data.handle': route.params.handle },
  })
);
</script>

<template>
  <div v-if="!article && !isPreviewing()">404</div>
  <div v-if="article?.data" class="content">
    <h1>{{ article.data.title }}</h1>
    <p>{{ article.data.blurb }}</p>
    <img :src="article.data.image" alt="" />
    <Content :model="model" :content="article" :apiKey="API_KEY" />
  </div>
</template>

// packages/sdks/snippets/react-sdk-next-pages/src/pages/blogs/[handle].tsx
import {
  Content,
  fetchOneEntry,
  isPreviewing,
  type KhulnasoftContent,
} from '@khulnasoft.com/sdk-react';
import type { GetServerSideProps, InferGetServerSidePropsType } from 'next';

const MODEL_NAME = 'blog-article';
const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';

export const getServerSideProps = (async ({ params }) => {
  const article = await fetchOneEntry({
    model: MODEL_NAME,
    apiKey: API_KEY,
    query: { 'data.handle': params?.handle },
  });
  return { props: { article } };
}) satisfies GetServerSideProps<{
  article: KhulnasoftContent | null;
}>;

export default function BlogArticlePage({
  article,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  if (!article && !isPreviewing()) {
    return <div>404</div>;
  }
  return (
    article?.data && (
      <div className="content">
        <h1>{article.data.title}</h1>
        <p>{article.data.blurb}</p>
        <img src={article.data.image} alt={article.data.title} />
        <Content model={MODEL_NAME} content={article} apiKey={API_KEY} />
      </div>
    )
  );
}
