// packages/sdks/snippets/svelte/src/components/AnnouncementBar.svelte
<!-- https://www.khulnasoft.com/c/docs/integrate-section-building -->
<!-- https://www.khulnasoft.com/c/blueprints/announcement-bar -->
<!-- src/components/AnnouncementBar.svelte -->

<script lang="ts">
  import {
    Content,
    fetchOneEntry,
    type KhulnasoftContent,
  } from '@khulnasoft.com/sdk-svelte';

  let apiKey = 'ee9f13b4981e489a9a1209887695ef2b';
  let model = 'announcement-bar';

  let announcementBar: KhulnasoftContent | null = null;

  async function fetchContent() {
    announcementBar = await fetchOneEntry({
      apiKey,
      model,
      userAttributes: {
        urlPath: window.location.pathname,
      },
    });
  }

  fetchContent();
</script>

<main>
  {#if announcementBar}
    <Content content={announcementBar} {apiKey} {model} />
  {/if}
  
  <!-- Your content coming from your app (or also Khulnasoft) -->
  <div>The rest of your page goes here</div>
</main>

// packages/sdks/snippets/solidjs/src/components/AnnouncementBar.tsx
/**
 * https://www.khulnasoft.com/c/docs/integrate-section-building
 * https://www.khulnasoft.com/c/blueprints/announcement-bar
 * src/components/AnnouncementBar.tsx
 */
import {
  Content,
  fetchOneEntry,
  type KhulnasoftContent,
} from '@khulnasoft.com/sdk-solid';
import { createEffect, createSignal } from 'solid-js';

const KHULNASOFT_API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';
const MODEL = 'announcement-bar';

function AnnouncementBar() {
  const [content, setContent] = createSignal<KhulnasoftContent | null>(null);

  createEffect(() => {
    fetchOneEntry({
      model: MODEL,
      apiKey: KHULNASOFT_API_KEY,
      userAttributes: {
        urlPath: window.location.pathname,
      },
    }).then((data: any) => {
      setContent(data);
    });
  });

  return (
    <>
      {content() && (
        <Content content={content()} apiKey={KHULNASOFT_API_KEY} model={MODEL} />
      )}

      {/* Your content coming from your app (or also Khulnasoft) */}
      <div>The rest of your page goes here</div>
    </>
  );
}

export default AnnouncementBar;
