// packages/sdks/snippets/svelte/src/components/blueprints/BlogArticle.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    fetchOneEntry,
    Content,
    isPreviewing,
    type KhulnasoftContent,
  } from '@khulnasoft.com/sdk-svelte';

  export let handle: string;
  let article: KhulnasoftContent | null;
  const model = 'blog-article';
  const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

  onMount(() => {
    fetchOneEntry({
      model,
      apiKey,
      query: { 'data.handle': handle },
    }).then((data) => {
      article = data;
    });
  });
</script>

{#if !article?.data && !isPreviewing()}
  <div>404</div>
{:else if article?.data}
  <div class="content">
    <h1>{article.data.title}</h1>
    <p>{article.data.blurb}</p>
    <img src={article.data.image} alt={article.data.title} />
    <Content {model} content={article} {apiKey} />
  </div>
{/if}

// packages/sdks/snippets/angular-16/src/app/blog-article/blog-article.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import {
  Content,
  fetchOneEntry,
  type KhulnasoftContent,
} from '@khulnasoft.com/sdk-angular';

@Component({
  selector: 'app-blog-article',
  standalone: true,
  imports: [Content, CommonModule],
  template: `<div *ngIf="article" class="content">
    <h1>{{ article.data?.title }}</h1>
    <p>{{ article.data?.['blurb'] }}</p>
    <img [src]="article.data?.['image']" alt="" />
    <khulnasoft-content [model]="model" [content]="article"></khulnasoft-content>
  </div> `,
})
export class BlogArticleComponent {
  article: KhulnasoftContent | null = null;
  model = 'blog-article';

  async ngOnInit() {
    this.article = await fetchOneEntry({
      model: this.model,
      apiKey: 'ee9f13b4981e489a9a1209887695ef2b',
      query: {
        'data.handle': 'new-product-line',
      },
    });
  }
}
