// packages/sdks/snippets/react-sdk-next-14-app/app/advanced-child/page.tsx
// app/advanced-child/page.tsx
import { Content, fetchOneEntry, isPreviewing } from '@khulnasoft.com/sdk-react';
import { customTabsInfo } from '../components/CustomTabs';

const MODEL_NAME = 'advanced-child';
const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';

export default async function Page() {
  const content = await fetchOneEntry({
    model: MODEL_NAME,
    apiKey: API_KEY,
    userAttributes: { urlPath: '/advanced-child' },
  });

  if (!content && !isPreviewing()) {
    return <div>404</div>;
  }

  return (
    <Content
      content={content}
      model={MODEL_NAME}
      apiKey={API_KEY}
      customComponents={[customTabsInfo]}
    />
  );
}

// packages/sdks/snippets/nuxt/pages/advanced-child.vue
<script setup lang="ts">
import { Content, fetchOneEntry, isPreviewing } from '@khulnasoft.com/sdk-vue';
import CustomTabsInfo from '../components/CustomTabsInfo';
import { useRoute } from 'nuxt/app';

const route = useRoute();
const model = 'advanced-child';
const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

const { data: content, pending } = await useAsyncData(
  `khulnasoft-${model}-${route.path}`,
  () =>
    fetchOneEntry({
      model,
      apiKey,
      userAttributes: {
        urlPath: route.path,
      },
    })
);
</script>

<template>
  <div>
    <div v-if="pending">Loading...</div>
    <div v-else-if="!content && !isPreviewing()">404 - Not Found</div>
    <Content
      v-else
      :content="content"
      :model="model"
      :apiKey="apiKey"
      :customComponents="[CustomTabsInfo]"
    />
  </div>
</template>
