// packages/sdks/snippets/react-sdk-next-14-app/app/custom-child/page.tsx
// app/custom-child/page.tsx
import { Content, fetchOneEntry, isPreviewing } from '@khulnasoft.com/sdk-react';
import { customHeroInfo } from '../components/CustomHero';

const MODEL_NAME = 'custom-child';
const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';

export default async function Page() {
  const content = await fetchOneEntry({
    model: MODEL_NAME,
    apiKey: API_KEY,
    userAttributes: { urlPath: '/custom-child' },
  });

  if (!content && !isPreviewing()) {
    return <div>404</div>;
  }

  return (
    <Content
      content={content}
      model={MODEL_NAME}
      apiKey={API_KEY}
      customComponents={[customHeroInfo]}
    />
  );
}

// packages/sdks/snippets/nuxt/pages/custom-child.vue
<script setup lang="ts">
import { fetchOneEntry, Content, isPreviewing } from '@khulnasoft.com/sdk-vue';
import CustomHeroInfo from '../components/CustomHeroInfo';
import { useRoute } from 'nuxt/app';

const route = useRoute();
const model = 'custom-child';
const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

const { data: content, pending } = await useAsyncData(
  `khulnasoft-${model}-${route.path}`,
  () =>
    fetchOneEntry({
      model,
      apiKey,
      userAttributes: {
        urlPath: route.path,
      },
    })
);
</script>

<template>
  <div v-if="pending">Loading...</div>
  <div v-else-if="!content && !isPreviewing()">404 - Not Found</div>
  <Content
    v-else
    :content="content"
    :model="model"
    :apiKey="apiKey"
    :customComponents="[CustomHeroInfo]"
  />
</template>
