// packages/sdks/snippets/qwik-city/src/routes/editable-region/index.tsx
import { component$ } from '@khulnasoft.com/qwik';
import { routeLoader$ } from '@khulnasoft.com/qwik-city';
import { Content, fetchOneEntry, isPreviewing } from '@khulnasoft.com/sdk-qwik';
import { customColumnsInfo } from '~/components/CustomColumns';

const MODEL = 'editable-regions';
const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';

export const useCustomChild = routeLoader$(async ({ url }) => {
  return await fetchOneEntry({
    model: MODEL,
    apiKey: API_KEY,
    userAttributes: {
      urlPath: url.pathname,
    },
  });
});

export default component$(() => {
  const content = useCustomChild();

  if (!content.value && !isPreviewing()) {
    return <div>404</div>;
  }
  return (
    <Content
      model={MODEL}
      content={content.value}
      apiKey={API_KEY}
      customComponents={[customColumnsInfo]}
    />
  );
});

// packages/sdks/snippets/nuxt/pages/editable-region.vue
<template>
  <div>
    <div v-if="pending">Loading...</div>
    <div v-else-if="!content && !isPreviewing()">404 - Not Found</div>
    <Content
      v-else
      :content="content"
      :model="model"
      :apiKey="apikey"
      :customComponents="[CustomColumnsInfo]"
    />
  </div>
</template>

<script setup lang="ts">
import { Content, fetchOneEntry, isPreviewing } from '@khulnasoft.com/sdk-vue';
import CustomColumnsInfo from '../components/CustomColumnsInfo';
import { useRoute } from 'nuxt/app';

const route = useRoute();
const model = 'editable-regions';
const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

const { data: content, pending } = await useAsyncData(
  `khulnasoft-${model}-${route.path}`,
  () =>
    fetchOneEntry({
      model,
      apiKey,
      userAttributes: { urlPath: route.path },
    })
);
</script>
