// packages/sdks/snippets/nuxt/pages/editable-region.vue
<template>
  <div>
    <div v-if="pending">Loading...</div>
    <div v-else-if="!content && !isPreviewing()">404 - Not Found</div>
    <Content
      v-else
      :content="content"
      :model="model"
      :apiKey="apikey"
      :customComponents="[CustomColumnsInfo]"
    />
  </div>
</template>

<script setup lang="ts">
import { Content, fetchOneEntry, isPreviewing } from '@khulnasoft.com/sdk-vue';
import CustomColumnsInfo from '../components/CustomColumnsInfo';
import { useRoute } from 'nuxt/app';

const route = useRoute();
const model = 'editable-regions';
const apiKey = 'ee9f13b4981e489a9a1209887695ef2b';

const { data: content, pending } = await useAsyncData(
  `khulnasoft-${model}-${route.path}`,
  () =>
    fetchOneEntry({
      model,
      apiKey,
      userAttributes: { urlPath: route.path },
    })
);
</script>

// packages/sdks/snippets/react-sdk-next-14-app/app/editable-region/page.tsx
// app/editable-region/page.tsx
import { Content, fetchOneEntry, isPreviewing } from '@khulnasoft.com/sdk-react';
import { customColumnsInfo } from '../components/CustomColumns';

const MODEL_NAME = 'editable-regions';
const API_KEY = 'ee9f13b4981e489a9a1209887695ef2b';

export default async function Page() {
  const content = await fetchOneEntry({
    model: MODEL_NAME,
    apiKey: API_KEY,
    userAttributes: { urlPath: '/editable-region' },
  });

  if (!content && !isPreviewing()) {
    return <div>404</div>;
  }

  return (
    <Content
      content={content}
      model={MODEL_NAME}
      apiKey={API_KEY}
      customComponents={[customColumnsInfo]}
    />
  );
}
