// examples/angular-gen2/src/app/catch-all.component.ts
import { Component } from '@angular/core';
import {
  Content,
  fetchOneEntry,
  getKhulnasoftSearchParams,
  type KhulnasoftContent,
} from '@khulnasoft.com/sdk-angular';

import { environment } from '../environments/environment';

@Component({
  selector: 'catch-all-route',
  standalone: true,
  template: `
    @if (content) {
      <khulnasoft-content
        [model]="model"
        [content]="content"
        [apiKey]="apiKey"
      ></khulnasoft-content>
    } @else {
      <div>404 - Content not found</div>
    }
  `,
  imports: [Content],
})
export class CatchAllComponent {
    model = "page";
    apiKey = environment.khulnasoftApiKey;
    content: KhulnasoftContent | null = null;

  async ngOnInit() {
    const khulnasoftContent = await fetchOneEntry({
      model: this.model,
      apiKey: this.apiKey,
      options: getKhulnasoftSearchParams(new URLSearchParams(window.location.search)),
      userAttributes: { urlPath: window.location.pathname },
    });

    if (!khulnasoftContent) {
      return;
    }

    this.content = khulnasoftContent;
  }
}

// packages/sdks/snippets/svelte/src/components/CatchAll.svelte
<!-- Quickstart snippet -->
<!-- snippets/svelte/src/components/CatchAll.svelte -->

<script lang="ts">
    import { Content, fetchOneEntry, type KhulnasoftContent } from '@khulnasoft.com/sdk-svelte';

    let apiKey = 'ee9f13b4981e489a9a1209887695ef2b';
    let model = 'page';

    let content: KhulnasoftContent | null = null;

    async function fetchContent() {
        content = await fetchOneEntry({
            apiKey,
            model,
            userAttributes: {
                urlPath: window.location.pathname
            }
        });
    }

    fetchContent();
</script>

<svelte:head>
    <title>{content?.data?.title || "Unpublished"}</title>
</svelte:head>

<main>
    {#if content}
        <Content content={content} apiKey={apiKey} model={model}  />
    {:else}
        Content Not Found
    {/if}
</main>
