// packages/sdks/snippets/angular-16-ssr/src/app/editable-regions/custom-columns/custom-columns.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import type {
  KhulnasoftBlock,
  KhulnasoftContextInterface,
  RegisteredComponent,
  RegisteredComponents,
} from '@khulnasoft.com/sdk-angular';
import { Blocks } from '@khulnasoft.com/sdk-angular';

@Component({
  selector: 'app-custom-columns',
  standalone: true,
  imports: [CommonModule, Blocks],
  template: `
    <blocks
      [blocks]="column1"
      [path]="'column1'"
      [parent]="khulnasoftBlock.id"
      [context]="khulnasoftContext"
      [registeredComponents]="khulnasoftComponents"
    />
    <blocks
      [blocks]="column2"
      [path]="'column2'"
      [parent]="khulnasoftBlock.id"
      [context]="khulnasoftContext"
      [registeredComponents]="khulnasoftComponents"
    />
  `,
})
export class CustomColumnsComponent {
  @Input() khulnasoftBlock!: KhulnasoftBlock;
  @Input() column1!: KhulnasoftBlock[];
  @Input() column2!: KhulnasoftBlock[];
  @Input() khulnasoftComponents!: RegisteredComponents;
  @Input() khulnasoftContext!: KhulnasoftContextInterface;
}

export const customColumnsInfo: RegisteredComponent = {
  name: 'MyColumns',
  component: CustomColumnsComponent,
  inputs: [
    {
      name: 'column1',
      type: 'uiBlocks',
      defaultValue: [],
    },
    {
      name: 'column2',
      type: 'uiBlocks',
      defaultValue: [],
    },
  ],

  shouldReceiveKhulnasoftProps: {
    khulnasoftBlock: true,
    khulnasoftComponents: true,
    khulnasoftContext: true,
  },
};

// packages/sdks/snippets/qwik-city/src/components/CustomColumns.tsx
import { component$ } from '@khulnasoft.com/qwik';
import {
  Blocks,
  type KhulnasoftBlock,
  type RegisteredComponent,
} from '@khulnasoft.com/sdk-qwik';

export const CustomColumns = component$(
  (props: {
    column1: KhulnasoftBlock[];
    column2: KhulnasoftBlock[];
    khulnasoftBlock: KhulnasoftBlock;
  }) => {
    return (
      <>
        <Blocks
          blocks={props.column1}
          path="column1"
          parent={props.khulnasoftBlock.id}
        />

        <Blocks
          blocks={props.column2}
          path="column2"
          parent={props.khulnasoftBlock.id}
        />
      </>
    );
  }
);

export const customColumnsInfo: RegisteredComponent = {
  name: 'MyColumns',
  component: CustomColumns,
  shouldReceiveKhulnasoftProps: {
    khulnasoftBlock: true,
  },

  inputs: [
    {
      name: 'column1',
      type: 'uiBlocks',
      defaultValue: [],
    },
    {
      name: 'column2',
      type: 'uiBlocks',
      defaultValue: [],
    },
  ],
};
